services:
  postgres:
    image: postgres:16
    container_name: league_predictor_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: league_admin
      POSTGRES_PASSWORD: league_pw
      POSTGRES_DB: league_predictor
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    container_name: league_predictor_cache
    restart: unless-stopped
    ports:
      - "6380:6379"

  api:
    build: .
    container_name: league_predictor_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://league_admin:league_pw@postgres:5432/league_predictor
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  prometheus:
    image: prom/prometheus
    container_name: league_predictor_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    container_name: league_predictor_grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

volumes:
  pgdata: